[env:lilygo_t_dongle_s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
extra_scripts = pre:../scripts/generate_macro_policy.py
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D SAFE_MACRO_AP_SSID=\"DONGL\"
  -D SAFE_MACRO_AP_PASS=\"dongl1234\"
